### ISSUE TITLE
Make it availible for the users (e.g. openrepos or jolla store)

### ISSUE THREAD

**Issue by jsaalfeld** [r0kk3rz/harbour-matrix#2]
Hi there,

I really want to test a native matrix client, but I don't want to do the whole dev-setup on my local machine to receive an installable package. It would be nice to just pull it from openrepos or the jolla store.

**Comment by Thra11** [comment]
Or if you're not ready to push it to the stores, just providing rpm releases to download from github could be a handy intermediate step to allow people to test it more easily.

**Comment by Thra11** [comment]
*Although that only works if it doesn't have hundreds of dependencies that aren't available from repos.

**Comment by r0kk3rz** [comment]
Builds are available from Mer OBS:
https://build.merproject.org/package/show/home:r0kk3rz/harbour-matrix

**Comment by rinigus** [comment]
True, builds are available there, but it would help the visibility if you could publish it at OpenRepos. I would suggest to consider it, please
